DROP TABLE IF EXISTS ExchangeRates;
CREATE TABLE IF NOT EXISTS ExchangeRates(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	BaseCurrencyId INTEGER NOT NULL,
	TargetCurrencyId INTEGER NOT NULL,
	Rate REAL NOT NULL,
	FOREIGN KEY (BaseCurrencyId) REFERENCES Currencies (ID) ON DELETE CASCADE,
	FOREIGN KEY (TargetCurrencyId) REFERENCES Currencies (ID) ON DELETE CASCADE
);